sizes:
  cell: 25 # snake cell = 25x25 pixels
  vector: 5 # x = -5..5 && y = -5..5

colors:
  snake: 'red'
  apple: 'green'
  background: 'white'
  wall: 'gray'

game:
  only_command_line_output: false
  step_delay: 0.1

learning:
  weights: '1650378163_18014398511655888.txt' # weights to load in first generation
  available_steps_without_apple: 150
  number_of_snakes_in_generation: 1500
  number_of_generations: 100
  mutation_rate: 3
  mutation_scale: 0.2
