sizes:
  cell: 35
  vector: 5

colors:
  snake: 'red'
  apple: 'green'
  background: 'white'
  wall: 'gray'

game:
  only_command_line_output: false
  step_delay: 0.03

learning:
  weights: '1650746992_37778931862957170098176.txt'
  available_steps_without_apple: 150
  number_of_snakes_in_generation: 1000
  number_of_parents_in_generation: 500
  number_of_generations: 500
  mutation_rate: 5
  mutation_scale: 0.2
